[[main]]
  name = "ğŸ  ãƒ›ãƒ¼ãƒ "
  pageRef = "/"
  weight = 1

[[main]]
  name = "è¨˜äº‹ä¸€è¦§"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "ã‚¿ã‚°"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "ã‚«ãƒ†ã‚´ãƒª"
  pageRef = "categories"
  weight = 30
